# Generated by Django 4.2.10 on 2025-03-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['name'], name='candidates__name_ed6dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['email'], name='candidates__email_188e48_idx'),
        ),
    ]
